export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const LOGIN_CUSTOMER = "LOGIN_CUSTOMER";
export const LOGIN_EMPLOYEE = "LOGIN_EMPLOYEE";
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGOUT = "LOGOUT";
export const WRONG_LOGGING = "WRONG_LOGGING";

export const FETCH_INFO = "FETCH_INFO";
export const FETCH_LIST_ACCOUNT = "FETCH_LIST_ACCOUNT";
export const FETCH_RECEIVERS = "FETCH_RECEIVERS";
export const ADD_RECEIVER = "ADD_RECEIVER";
export const REMOVE_RECEIVER = "REMOVE_RECEIVER";
export const CHANGE_RECEIVER = "CHANGE_RECEIVER";
export const FETCH_LIST_DEBTOR = "FETCH_LIST_DEBTOR";

export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const GET_HISTORY = "GET_HISTORY";
export const FETCH_HISTORY = "FETCH_HISTORY";
export const FETCH_LIST_PAYIN = "FETCH_LIST_PAYIN";
export const FETCH_LIST_TRANSER = "FETCH_LIST_TRANSER";
export const FETCH_LIST_DEBT = "FETCH_LIST_DEBT";
export const FETCH_ALL_TYPES_TRANS = "FETCH_ALL_TYPES_TRANS";

export const FETCH_LIST_EMPLOYEE = "FETCH_LIST_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
